// <auto-generated />
namespace BookingOffice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class addTimeMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTimeMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201910061822292_addTimeMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
